# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 21:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couple', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='uploaded_photos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('address', models.TextField(default='No Address Provided')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('allotted_hours', models.PositiveSmallIntegerField()),
                ('capacity', models.PositiveSmallIntegerField()),
                ('alcohol_situation', models.CharField(choices=[(0, 'Alcohol provider of choice'), (1, 'Alcohol provided by venue'), (2, 'No Alcohol')], default=1, max_length=1)),
                ('alcohol_pricing', models.TextField(default='')),
                ('food_situation', models.CharField(choices=[(0, 'Must use provided catering'), (1, 'Must choose from approved caterers'), (2, 'Any caterer is fine')], default=1, max_length=1)),
                ('logistics_comments', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wedding.Venue'),
        ),
    ]
