# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_auto_20170903_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='_address_rendered',
            field=models.TextField(default='No Address Provided', editable=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='address_markup_type',
            field=models.CharField(blank=True, choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('restructuredtext', 'Restructured Text'),
                                                        ('markdown', 'Markdown')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=markupfield.fields.MarkupField(default='No Address Provided', rendered_field=True),
        ),
    ]
