# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_auto_20170903_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.FileField(blank=True, null=True, upload_to='uploaded_photos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='UploadedPhoto',
        ),
        migrations.AddField(
            model_name='venue',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_photos'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address_markup_type',
            field=models.CharField(blank=True, choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown'), ('restructuredtext', 'Restructured Text')], default=None, max_length=30, null=True),
        ),
    ]
