# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0008_auto_20170904_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
