# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0009_auto_20170904_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
