# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0011_auto_20170928_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.FileField(blank=True, null=True, upload_to='uploaded_photos')),
                ('page', models.CharField(choices=[('Home', 'Home'), ('Food', 'Food'), ('Contact', 'Contact'), ('Gifts', 'Gifts'), ('Venue', 'Venue'), ('RSVP', 'RSVP')], default='Home', max_length=10)),
                ('header', models.TextField(default='')),
                ('content', markupfield.fields.MarkupField(default='No Content', rendered_field=True)),
                ('content_markup_type', models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown'), ('restructuredtext', 'Restructured Text')], default='markdown', max_length=30)),
                ('_content_rendered', models.TextField(default='No Content', editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BackgroundPhoto',
        ),
    ]
