# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0012_auto_20170930_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='content_markup_type',
            new_name='description_markup_type',
        ),
        migrations.RemoveField(
            model_name='page',
            name='_content_rendered',
        ),
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.RemoveField(
            model_name='page',
            name='page',
        ),
        migrations.AddField(
            model_name='page',
            name='_description_rendered',
            field=models.TextField(default='No Description Provided', editable=False),
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=markupfield.fields.MarkupField(default='No Description Provided', rendered_field=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.Page'),
        ),
    ]
