# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0013_auto_20170930_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.CharField(default='food', max_length=100),
            preserve_default=False,
        ),
    ]
