# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0014_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
