# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0015_auto_20170930_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='header',
            field=models.CharField(default='Fooooood', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='header',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
