# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0017_auto_20171001_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.FileField(blank=True, null=True, upload_to='uploaded_photos')),
                ('rank', models.PositiveSmallIntegerField(help_text='Lower is better.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
